// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using t01efc.Data;

#nullable disable

namespace t01efc.Migrations
{
    [DbContext(typeof(GamesDbContext))]
    [Migration("20260930102802_Developers")]
    partial class Developers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("DeveloperGame", b =>
                {
                    b.Property<int>("DevelopersDeveloperId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GamesGameId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DevelopersDeveloperId", "GamesGameId");

                    b.HasIndex("GamesGameId");

                    b.ToTable("DeveloperGame");
                });

            modelBuilder.Entity("t01efc.Models.Developer", b =>
                {
                    b.Property<int>("DeveloperId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DeveloperId");

                    b.ToTable("Developer");

                    b.HasData(
                        new
                        {
                            DeveloperId = 1,
                            Name = "CD Projekt Red"
                        },
                        new
                        {
                            DeveloperId = 2,
                            Name = "Bethesda Game Studios"
                        },
                        new
                        {
                            DeveloperId = 3,
                            Name = "Rockstar Games"
                        },
                        new
                        {
                            DeveloperId = 4,
                            Name = "Valve Corporation"
                        },
                        new
                        {
                            DeveloperId = 5,
                            Name = "Ubisoft"
                        });
                });

            modelBuilder.Entity("t01efc.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenreId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GameId");

                    b.HasIndex("GenreId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("t01efc.Models.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GenreId");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            Text = "Action"
                        },
                        new
                        {
                            GenreId = 2,
                            Text = "RPG"
                        },
                        new
                        {
                            GenreId = 3,
                            Text = "Adventure"
                        },
                        new
                        {
                            GenreId = 4,
                            Text = "Strategy"
                        },
                        new
                        {
                            GenreId = 5,
                            Text = "Simulation"
                        });
                });

            modelBuilder.Entity("DeveloperGame", b =>
                {
                    b.HasOne("t01efc.Models.Developer", null)
                        .WithMany()
                        .HasForeignKey("DevelopersDeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("t01efc.Models.Game", null)
                        .WithMany()
                        .HasForeignKey("GamesGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("t01efc.Models.Game", b =>
                {
                    b.HasOne("t01efc.Models.Genre", "Genre")
                        .WithMany("Games")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("t01efc.Models.Genre", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
